Update websockets
mason-at-pieces/pieces-copilot-python-sdk pull request #5
Opened 2024-08-07 23:51 UTC by Bishoy-at-pieces

2024-08-07 23:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mason-at-pieces/pieces-copilot-python-sdk?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mason-at-pieces/pieces-copilot-python-sdk?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mason-at-pieces/pieces-copilot-python-sdk?pullRequest=5) it.</sub>

2024-08-12 22:32 UTC, mason-at-pieces commented
@Bishoy-at-pieces could you please add in a file that displays the use cases for the added methods?

I have written tests for the original methods and will merge them in but just need to ensure that this all works. Also need to ensure that we are good with the experience that this gives a developer

2024-08-12 22:38 UTC, Bishoy-at-pieces commented
docs/caching.md
docs/wevsockets.md

2024-08-12 22:40 UTC, Bishoy-at-pieces commented
Bow it is much much easier to interact with assets and conversations is cached so anything related to conversation instead of fetching the api you should use the cache

2024-08-20 02:20 UTC, masnwilliams requested changes

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +def test_raw_property(mock_asset_snapshot, mock_asset):
should be named `test_raw_content_property` since we updated `raw` to `raw_content`

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +    assert asset.raw == "Test content"
`.raw` need to be updated to `.raw_content`

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +        mock_format.fragment.string.raw = "Test content"
`.raw` need to be updated to `.raw_content`

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +        asset.raw = new_content
`.raw` need to be updated to `.raw_content`

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +        assert mock_format.fragment.string.raw == new_content
`.raw` need to be updated to `.raw_content`

2024-08-20 02:20 UTC, masnwilliams commented on tests/test_basic_asset.py
> +    mock.original.reference.fragment.string.raw = "Test content"
`.raw` need to be updated to `.raw_content`

2024-08-20 02:21 UTC, masnwilliams commented on tests/test_basic_asset.py
> +    return PiecesClient(config={'baseUrl': 'http://localhost:1000/'})
would rather us keep urls to not include ending `/`. so this should be just `http://localhost:1000`

2024-08-20 07:20 UTC, shivay-at-pieces commented on docs/basic_message.md
> +
Describe here how a message is related to a Copilot chat/conversation

2024-08-20 10:15 UTC, shivay-at-pieces commented on docs/copilot.md
> +    pipeline (Optional[QGPTPromptPipeline]): the pipeline to use.
Should we document the different pipelines?

2024-08-20 10:28 UTC, Bishoy-at-pieces commented on docs/copilot.md
> +    pipeline (Optional[QGPTPromptPipeline]): the pipeline to use.
The pipelines should be already documented on the website docs we can an anchor

2024-08-20 10:38 UTC, Bishoy-at-pieces commented on tests/test_basic_asset.py
> +    mock.original.reference.fragment.string.raw = "Test content"
This is raw as it is (not a method it is an asset mock)

2024-08-21 21:59 UTC, shivay-at-pieces commented on docs/basic_chat.md
> +    print(f"Message: {message.raw}")
raw_content

2024-08-22 12:27 UTC, Bishoy-at-pieces commented
Should I close that PR and open it again on the new repo??

2024-08-22 18:43 UTC, closed without merging